# Generated by Django 6.1.1 on 2026-09-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable partition label', max_length=255)),
                ('category', models.CharField(choices=[('apartment-sale', 'Apartment Sale / فروش آپارتمان'), ('house-villa-sale', 'House & Villa Sale / فروش خانه و ویلا'), ('land-sale', 'Land & Plot Sale / فروش زمین و کلنگی'), ('commercial-sale', 'Commercial Sale / فروش اداری و تجاری'), ('apartment-rent', 'Apartment Rent / رهن و اجاره آپارتمان'), ('house-villa-rent', 'House & Villa Rent / رهن و اجاره خانه و ویلا'), ('commercial-rent', 'Commercial Rent / رهن و اجاره اداری و تجاری')], db_index=True, default='apartment-sale', max_length=64)),
                ('city', models.CharField(db_index=True, default='tehran', max_length=64)),
                ('district', models.IntegerField(blank=True, db_index=True, help_text='Tehran District (1-22)', null=True)),
                ('neighborhood', models.CharField(blank=True, db_index=True, max_length=128)),
                ('min_area', models.IntegerField(blank=True, null=True)),
                ('max_area', models.IntegerField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, help_text='Minimum price in Tomans', null=True)),
                ('max_price', models.BigIntegerField(blank=True, help_text='Maximum price in Tomans', null=True)),
                ('min_rooms', models.IntegerField(blank=True, null=True)),
                ('max_rooms', models.IntegerField(blank=True, null=True)),
                ('only_with_parking', models.BooleanField(default=False)),
                ('only_with_elevator', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0, help_text='Listings found in last execution')),
                ('unique_listings_count', models.IntegerField(default=0, help_text='Unique new listings found')),
                ('duplicate_listings_count', models.IntegerField(default=0, help_text='Duplicate listings already observed')),
                ('successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district', 'category', 'min_area'],
                'indexes': [models.Index(fields=['city', 'district', 'category'], name='ingestion_s_city_9c596e_idx'), models.Index(fields=['active', 'last_run'], name='ingestion_s_active_c39b62_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('number_of_results', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('partition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='ingestion.searchpartition')),
            ],
            options={
                'ordering': ['-request_time'],
                'indexes': [models.Index(fields=['request_time', 'http_status'], name='ingestion_a_request_e8a12b_idx')],
            },
        ),
    ]
