# Generated by Django 6.1.1 on 2026-09-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(db_index=True, help_text='tehran, district, neighborhood, property_type, area_range, age_range', max_length=32)),
                ('dimension_value', models.CharField(db_index=True, help_text='overall, district-1, saadat-abad, 50-70, etc.', max_length=128)),
                ('dimension_label_fa', models.CharField(blank=True, max_length=128)),
                ('transaction_type', models.CharField(db_index=True, default='sale', help_text='sale or rent', max_length=16)),
                ('listing_count', models.IntegerField(default=0)),
                ('median_price', models.BigIntegerField(blank=True, null=True)),
                ('mean_price', models.BigIntegerField(blank=True, null=True)),
                ('median_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('mean_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('min_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('max_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('q1_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('q3_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('mad', models.FloatField(blank=True, null=True)),
                ('percentiles', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['dimension', 'dimension_value'],
                'indexes': [models.Index(fields=['dimension', 'transaction_type'], name='analytics_m_dimensi_2950a9_idx')],
                'unique_together': {('dimension', 'dimension_value', 'transaction_type')},
            },
        ),
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_name', models.CharField(db_index=True, help_text='iqr, robust_zscore, isolation_forest, comparable_deviation, ensemble', max_length=64)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('explanation', models.TextField(blank=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('confidence', models.CharField(choices=[('strong', 'Strong Evidence / شواهد قوی'), ('moderate', 'Moderate Evidence / شواهد متوسط'), ('weak', 'Weak Evidence / شواهد ضعیف'), ('insufficient_data', 'Insufficient Data / داده ناکافی')], db_index=True, default='insufficient_data', max_length=32)),
                ('metrics', models.JSONField(default=dict, help_text='Stored metrics (median, Q1, Q3, MAD, deviation %)')),
                ('calculated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_results', to='listings.divarlisting')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['listing', 'detector_name'], name='analytics_a_listing_b43bf4_idx'), models.Index(fields=['is_anomaly', 'confidence'], name='analytics_a_is_anom_f7548c_idx')],
            },
        ),
    ]
