# Generated by Django 6.1.1 on 2026-09-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divar_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('apartment-sale', 'Apartment Sale / فروش آپارتمان'), ('house-villa-sale', 'House & Villa Sale / فروش خانه و ویلا'), ('land-sale', 'Land & Plot Sale / فروش زمین و کلنگی'), ('commercial-sale', 'Commercial Sale / فروش اداری و تجاری'), ('apartment-rent', 'Apartment Rent / رهن و اجاره آپارتمان'), ('house-villa-rent', 'House & Villa Rent / رهن و اجاره خانه و ویلا'), ('commercial-rent', 'Commercial Rent / رهن و اجاره اداری و تجاری')], db_index=True, max_length=64)),
                ('city', models.CharField(db_index=True, default='tehran', max_length=64)),
                ('district', models.IntegerField(blank=True, db_index=True, help_text='Tehran District 1-22', null=True)),
                ('neighborhood', models.CharField(blank=True, db_index=True, max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address_text', models.CharField(blank=True, max_length=512)),
                ('price', models.BigIntegerField(blank=True, db_index=True, help_text='Total price in Tomans (sale)', null=True)),
                ('price_mode', models.CharField(default='total', help_text='total, agreement, per_meter', max_length=32)),
                ('rent', models.BigIntegerField(blank=True, help_text='Monthly rent in Tomans', null=True)),
                ('deposit', models.BigIntegerField(blank=True, help_text='Mortgage / deposit in Tomans', null=True)),
                ('area_m2', models.FloatField(blank=True, db_index=True, null=True)),
                ('price_per_m2', models.BigIntegerField(blank=True, db_index=True, help_text='Sale price per m² in Tomans', null=True)),
                ('rent_per_m2', models.BigIntegerField(blank=True, help_text='Rent per m² in Tomans', null=True)),
                ('deposit_per_m2', models.BigIntegerField(blank=True, help_text='Deposit per m² in Tomans', null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('building_age', models.IntegerField(blank=True, help_text='Age in years', null=True)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('construction_type', models.CharField(blank=True, max_length=64)),
                ('property_type', models.CharField(blank=True, max_length=64)),
                ('seller_type', models.CharField(blank=True, help_text='personal, real_estate_agency', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('raw_json', models.JSONField(default=dict)),
                ('anomaly_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('anomaly_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['city', 'district', 'category'], name='listings_di_city_b05cc8_idx'), models.Index(fields=['district', 'area_m2', 'price_per_m2'], name='listings_di_distric_7c0b92_idx'), models.Index(fields=['is_anomaly', 'anomaly_score'], name='listings_di_is_anom_1a6266_idx'), models.Index(fields=['published_at', 'status'], name='listings_di_publish_2dfc09_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('rent', models.BigIntegerField(blank=True, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('raw_json', models.JSONField(default=dict)),
                ('price_change_absolute', models.BigIntegerField(default=0)),
                ('price_change_percent', models.FloatField(default=0.0)),
                ('price_per_m2_change', models.BigIntegerField(default=0)),
                ('event_type', models.CharField(db_index=True, default='initial', max_length=32)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='listings.divarlisting')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['listing', 'captured_at'], name='listings_li_listing_67a7a8_idx'), models.Index(fields=['event_type', 'captured_at'], name='listings_li_event_t_8296ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchPartitionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('is_new_listing', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partition_executions', to='listings.divarlisting')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ingestion.searchpartition')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['partition', 'executed_at'], name='listings_se_partiti_e1d485_idx')],
                'unique_together': {('partition', 'listing')},
            },
        ),
    ]
